import { AFRICAN_COUNTRIES, DEFAULT_LISTING_COUNTRY } from "@/lib/african-countries";

/** ITU calling codes for every African country on the site. */
export const AFRICA_DIAL_CODES: Record<string, string> = {
  Kenya: "+254",
  Algeria: "+213",
  Angola: "+244",
  Benin: "+229",
  Botswana: "+267",
  "Burkina Faso": "+226",
  Burundi: "+257",
  "Cabo Verde": "+238",
  Cameroon: "+237",
  "Central African Republic": "+236",
  Chad: "+235",
  Comoros: "+269",
  Congo: "+242",
  "Côte d'Ivoire": "+225",
  "Democratic Republic of the Congo": "+243",
  Djibouti: "+253",
  Egypt: "+20",
  "Equatorial Guinea": "+240",
  Eritrea: "+291",
  Eswatini: "+268",
  Ethiopia: "+251",
  Gabon: "+241",
  Gambia: "+220",
  Ghana: "+233",
  Guinea: "+224",
  "Guinea-Bissau": "+245",
  Lesotho: "+266",
  Liberia: "+231",
  Libya: "+218",
  Madagascar: "+261",
  Malawi: "+265",
  Mali: "+223",
  Mauritania: "+222",
  Mauritius: "+230",
  Morocco: "+212",
  Mozambique: "+258",
  Namibia: "+264",
  Niger: "+227",
  Nigeria: "+234",
  Rwanda: "+250",
  "São Tomé and Príncipe": "+239",
  Senegal: "+221",
  Seychelles: "+248",
  "Sierra Leone": "+232",
  Somalia: "+252",
  "South Africa": "+27",
  "South Sudan": "+211",
  Sudan: "+249",
  Tanzania: "+255",
  Togo: "+228",
  Tunisia: "+216",
  Uganda: "+256",
  Zambia: "+260",
  Zimbabwe: "+263",
};

const MOBILE_MONEY_BY_COUNTRY: Record<string, string[]> = {
  Kenya: ["M-Pesa", "Airtel Money"],
  Tanzania: ["M-Pesa", "Airtel Money", "Tigo Pesa", "HaloPesa"],
  Uganda: ["MTN MoMo", "Airtel Money"],
  Rwanda: ["MTN MoMo", "Airtel Money"],
  Ghana: ["MTN MoMo", "Telecel Cash", "AirtelTigo Money"],
  Nigeria: ["OPay", "PalmPay", "Paga", "OWealth"],
  "South Africa": ["Capitec Pay", "FNB eWallet", "Standard Bank Instant Money"],
  "Côte d'Ivoire": ["Orange Money", "MTN MoMo", "Moov Money", "Wave"],
  Senegal: ["Wave", "Orange Money", "Free Money"],
  Cameroon: ["MTN MoMo", "Orange Money"],
  "Democratic Republic of the Congo": ["M-Pesa", "Orange Money", "Airtel Money"],
  Congo: ["Airtel Money", "MTN MoMo"],
  Egypt: ["Vodafone Cash", "Orange Cash", "e& Cash"],
  Morocco: ["Orange Money", "inwi money"],
  Ethiopia: ["Telebirr", "M-Pesa"],
  Mozambique: ["M-Pesa", "e-Mola"],
  Zambia: ["Airtel Money", "MTN MoMo", "Zamtel Kwacha"],
  Zimbabwe: ["EcoCash", "OneMoney", "InnBucks"],
  Malawi: ["Airtel Money", "TNM Mpamba"],
  Madagascar: ["MVola", "Orange Money", "Airtel Money"],
  Mali: ["Orange Money", "Moov Money"],
  "Burkina Faso": ["Orange Money", "Moov Money"],
  Benin: ["MTN MoMo", "Moov Money"],
  Togo: ["TMoney", "Flooz"],
  Niger: ["Airtel Money", "Moov Money"],
  Guinea: ["Orange Money", "MTN MoMo"],
  "Sierra Leone": ["Orange Money", "Afrimoney"],
  Liberia: ["Orange Money", "Lonestar MTN"],
  Gambia: ["Afrimoney", "QMoney"],
  Gabon: ["Airtel Money", "Moov Money"],
  Chad: ["Airtel Money", "Moov Money"],
  "Central African Republic": ["Orange Money"],
  Burundi: ["Lumicash", "EcoCash"],
  "South Sudan": ["m-Gurush", "NilePay"],
  Somalia: ["EVC Plus", "Zaad", "eDahab"],
  Sudan: ["Bankak", "Fawri"],
  Tunisia: ["D17", "Flouci"],
  Algeria: ["BaridiMob", "Chargily"],
  Angola: ["Multicaixa Express"],
  Botswana: ["Orange Money", "MyZaka"],
  Namibia: ["MTC Play", "PayToday"],
  Lesotho: ["M-Pesa", "EcoCash"],
  Eswatini: ["MoMo", "eMali"],
  Mauritius: ["Juice", "Blink"],
  Seychelles: ["Absa", "MCB Juice"],
  Djibouti: ["Waafi", "D-Money"],
  Eritrea: ["Hadas Mobile"],
  Comoros: ["MVola", "Money Express"],
  "Cabo Verde": ["T-bank", "vinti4"],
  "Guinea-Bissau": ["Orange Money"],
  Mauritania: ["Bankily", "Masrvi"],
  "Equatorial Guinea": ["Muni", "Muni Money"],
  "São Tomé and Príncipe": ["CST Mobile"],
};

export const DIGITAL_WALLET_PROVIDERS = [
  "PayPal",
  "Wise",
  "Wave",
  "Chipper Cash",
  "OPay",
  "PalmPay",
  "Flutterwave",
  "Other",
] as const;

export function dialCodeForCountry(country?: string | null) {
  return AFRICA_DIAL_CODES[country || DEFAULT_LISTING_COUNTRY] ?? "+254";
}

export function mobileMoneyProvidersFor(country?: string | null) {
  const list =
    MOBILE_MONEY_BY_COUNTRY[country || DEFAULT_LISTING_COUNTRY] ?? [
      "Mobile money",
    ];
  return list.includes("Other") ? list : [...list, "Other"];
}

export const PAYOUT_COUNTRIES = AFRICAN_COUNTRIES;
