-- AlterTable
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "listAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "memberDiscountAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "memberLevel" INTEGER NOT NULL DEFAULT 1;

UPDATE "Booking"
SET "listAmount" = "totalAmount"
WHERE "listAmount" = 0;

-- AlterTable
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "bookingId" TEXT;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "cleanliness" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "locationScore" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "value" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "comfort" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "staff" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "liked" TEXT;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "disliked" TEXT;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "hostReply" TEXT;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "hostRepliedAt" TIMESTAMP(3);

CREATE UNIQUE INDEX IF NOT EXISTS "Review_bookingId_key" ON "Review"("bookingId");

ALTER TABLE "Review" DROP CONSTRAINT IF EXISTS "Review_bookingId_fkey";
ALTER TABLE "Review"
  ADD CONSTRAINT "Review_bookingId_fkey"
  FOREIGN KEY ("bookingId") REFERENCES "Booking"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;
